### PR TITLE
Add migration plugin badges to the README

### PR DESCRIPTION
**Pull request by goosemania**
[noissue]

### CODE REVIEW

**Comment by ipanova** [comment]
looking at other plugins' badges i see also the FIPS status, does it makes sense to add it to the migration plugin as well?

**Comment by goosemania** [comment]
> looking at other plugins' badges i see also the FIPS status, does it makes sense to add it to the migration plugin as well?

migration plugin doesn't have fips job at the moment

**Comment by ipanova** [comment]
> > looking at other plugins' badges i see also the FIPS status, does it makes sense to add it to the migration plugin as well?
> 
> migration plugin doesn't have fips job at the moment

I'm aware of that. It will eventually.

**Comment by goosemania** [comment]
> > > looking at other plugins' badges i see also the FIPS status, does it makes sense to add it to the migration plugin as well?
> > 
> > 
> > migration plugin doesn't have fips job at the moment
> 
> I'm aware of that. It will eventually.

I do not know which path to the workflow to use if it doesn't exist yet. And I'm not sure that the standard one used by other plugins will be used in the migration, because it will likely have a different box and potentially a different workflow.
What do you want me to do with this PR?

**Comment by ipanova** [comment]
> > > > looking at other plugins' badges i see also the FIPS status, does it makes sense to add it to the migration plugin as well?
> > > 
> > > 
> > > migration plugin doesn't have fips job at the moment
> > 
> > 
> > I'm aware of that. It will eventually.
> 
> I do not know which path to the workflow to use if it doesn't exist yet. And I'm not sure that the standard one used by other plugins will be used in the migration, because it will likely have a different box and potentially a different workflow.
> What do you want me to do with this PR?

my suggestion was to add this line 
`* [Pulp Migration FIPS CI](https://github.com/pulp/pulp-2to3-migration/actions/workflows/fips.yml)`
but i have not tested when a badge is being provided a non existent path, maybe it's a problem. hence it was purely a suggestion with intention to spare a follow up pr.

**Review by ipanova — APPROVED** [review]

**Comment by fao89** [comment]
> looking at other plugins' badges i see also the FIPS status, does it makes sense to add it to the migration plugin as well?

actually, our FIPS CI times out, so we will probably remove it soon

**Pull request merged**
